version: 2
updates:
  - package-ecosystem: "npm" # pnpm
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      eslint:
        patterns:
          - "@eslint*"
          - "@typescript-eslint/*"
          - "typescript-eslint"
